services:
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appointment_db
    volumes:
      - ./src:/app/src
    networks:
      - appointment-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appointment_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - appointment-network

networks:
  appointment-network:
    driver: bridge

volumes:
  postgres-data:
